export const data = [
  {
    brand: "Hertog Jan Weizener",
    brewery: "Hertog Jan",
    labels: ["Weizen"],
    price: 2,
    alc: 6.5,
    stock: 0,
    volume: 30,
    drinktempc: 5,
  },
  {
    brand: "La Trappe Tripel",
    brewery: "Koningshoeven",
    labels: ["Tripel", "Trappist"],
    price: 1.7,
    alc: 8,
    stock: 1,
    volume: 30,
    drinktempc: 12,
  },
  {
    brand: "Tripel Karmeliet",
    brewery: "Bosteels",
    labels: ["Tripel"],
    price: 1.8,
    alc: 8.4,
    stock: 2,
    volume: 30,
    drinktempc: 8,
  },
  {
    brand: "Hertog Jan Grand Prestige",
    brewery: "Hertog Jan",
    labels: ["Gerstewijn"],
    price: 5.0,
    alc: 10,
    stock: 5,
    volume: 75,
    drinktempc: 12,
  },
];
